# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: ./.github/github-contribution-grid-snake.gif
          svg_out_path: ./.github/github-contribution-grid-snake.svg

      - name: Upload to repo
        run: |
          git fetch
          git checkout snake
          git config --global user.email "snake@akun.dev"
          git config --global user.name "Almaz Kunpeissov"
          git add -f ./.github/github-contribution-grid-snake.svg
          git commit -m "update the snake"
          git push origin shake --force
